variables:
  project:  './CommandScore/CommandScore.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  targetVersion: yy.M.$(build.buildId)

pool:
  vmImage: 'windows-latest'

trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - CommandScore/*
    - Build/*

pr: none

steps:

- checkout: self
  submodules: true
  fetchDepth: 10

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  displayName: 'Create CalVer Version'
  inputs:
    targetType: 'inline'
    script: |
      $dottedDate = (Get-Date).ToString("yy.M")
      $buildID = $($env:BUILD_BUILDID) 
      $newTargetVersion = "$dottedDate.$buildID"
      Write-Host "##vso[task.setvariable variable=targetVersion;]$newTargetVersion"
      Write-Host "Updated targetVersion to '$newTargetVersion'"

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) /p:Version=$(targetVersion)'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    buildProperties: 'Version="$(targetVersion)"'

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/CommandScore.$(targetVersion).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'
